---
propel: 
  _attributes: 
    noXsd: false
    defaultIdMethod: native
    package: lib.model
  rcpadidis: 
    refadi: 
      type: VARCHAR
      size: 8
      required: true
    fecadi: 
      type: DATE
      required: true
    anoadi: 
      type: VARCHAR
      size: 4
    desadi: 
      type: VARCHAR
      size: 250
    desanu: 
      type: VARCHAR
      size: 250
    adidis: 
      type: VARCHAR
      size: 1
    totadi: 
      type: NUMERIC
      size: 14
      scale: 2
    staadi: 
      type: VARCHAR
      size: 1
    numcom: 
      type: VARCHAR
      size: 8
    fecanu: 
      type: DATE
    peradi: 
      type: VARCHAR
      size: 2
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  rcpmovadi: 
    refadi: 
      type: VARCHAR
      size: 8
      required: true
    codpre: 
      type: VARCHAR
      size: 32
      required: true
    perpre: 
      type: VARCHAR
      size: 2
      required: true
    monmov: 
      type: NUMERIC
      size: 14
      scale: 2
    stamov: 
      type: VARCHAR
      size: 1
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
