---
propel: 
  _attributes: 
    noXsd: false
    defaultIdMethod: native
    package: lib.model
  cobdesdoc: 
    refdoc: 
      type: VARCHAR
      size: 10
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    coddes: 
      type: VARCHAR
      size: 4
      required: true
    fecdes: 
      type: DATE
    mondes: 
      type: NUMERIC
      size: 14
      scale: 2
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobdestra: 
    numtra: 
      type: VARCHAR
      size: 10
      required: true
    refdoc: 
      type: VARCHAR
      size: 10
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    coddes: 
      type: VARCHAR
      size: 4
      required: true
    fecdes: 
      type: DATE
    mondes: 
      type: NUMERIC
      size: 14
      scale: 2
    monret: 
      type: NUMERIC
      size: 14
      scale: 2
    monant: 
      type: NUMERIC
      size: 14
      scale: 2
    numcomret: 
      type: VARCHAR
      size: 50
      description: Número del comprobante de retención.
    feccomret: 
      type: DATE
      description: Fecha del comprobante de retención.
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobdetfor: 
    numtra: 
      type: VARCHAR
      size: 10
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    correl: 
      type: VARCHAR
      size: 3
      required: true
    numide: 
      type: VARCHAR
      size: 24
    codban: 
      type: VARCHAR
      size: 20
    monpag: 
      type: NUMERIC
      size: 14
      scale: 2
    fatippag_id: 
      type: INTEGER
      required: true
      foreignTable: fatippag
      foreignReference: id
    fadescripfac_id: 
      type: INTEGER
    notcres: 
      type: VARCHAR
      size: 2000
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobdettra: 
    numtra: 
      type: VARCHAR
      size: 10
      required: true
    refdoc: 
      type: VARCHAR
      size: 10
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    correl: 
      type: VARCHAR
      size: 3
      required: true
    monpag: 
      type: NUMERIC
      size: 14
      scale: 2
    mondsc: 
      type: NUMERIC
      size: 14
      scale: 2
    monrec: 
      type: NUMERIC
      size: 14
      scale: 2
    totpag: 
      type: NUMERIC
      size: 14
      scale: 2
    nroant: 
      type: VARCHAR
      size: 8
    monamo: 
      type: NUMERIC
      size: 14
      scale: 2
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobdocume: 
    refdoc: 
      type: VARCHAR
      size: 10
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    fecemi: 
      type: DATE
      required: true
    fecven: 
      type: DATE
    oridoc: 
      type: VARCHAR
      size: 3
    desdoc: 
      type: VARCHAR
      size: 3000
    mondoc: 
      type: NUMERIC
      size: 14
      scale: 2
    recdoc: 
      type: NUMERIC
      size: 14
      scale: 2
    dscdoc: 
      type: NUMERIC
      size: 14
      scale: 2
    abodoc: 
      type: NUMERIC
      size: 14
      scale: 2
    saldoc: 
      type: NUMERIC
      size: 14
      scale: 2
    desanu: 
      type: VARCHAR
      size: 100
    fecanu: 
      type: DATE
    stadoc: 
      type: VARCHAR
      size: 1
    numcom: 
      type: VARCHAR
      size: 8
    feccom: 
      type: DATE
    reffac: 
      type: VARCHAR
      size: 8
    fatipmov_id: 
      type: INTEGER
      required: true
      foreignTable: fatipmov
      foreignReference: id
    totret: 
      type: NUMERIC
      size: 14
      scale: 2
    totant: 
      type: NUMERIC
      size: 14
      scale: 2
    fadescripfac_id: 
      type: INTEGER
    reftra: 
      type: VARCHAR
      size: 10
    coddirec: 
      type: VARCHAR
      size: 32
      description: Código de la Dirección
    tradoc: 
      type: VARCHAR
      size: 1
      description: Documento Trasladado de periodo anterior
    refdocnc: 
      type: VARCHAR
      size: 10
      description: Referencia del documento para Documento Nota de Credito
    monexo: 
      type: NUMERIC
      size: 14
      scale: 2
      description: Monto Exonerado
    refdocnd: 
      type: VARCHAR
      size: 10
      description: Referencia del documento para Documento Nota de Débito
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobpagban: 
    codban: 
      type: VARCHAR
      size: 3
      required: true
    nomban: 
      type: VARCHAR
      size: 50
    dirban: 
      type: VARCHAR
      size: 100
    telban: 
      type: VARCHAR
      size: 15
    faxban: 
      type: VARCHAR
      size: 15
    emaban: 
      type: VARCHAR
      size: 40
    conban: 
      type: VARCHAR
      size: 50
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobpagemp: 
    codemp: 
      type: VARCHAR
      size: 3
    faxemp: 
      type: VARCHAR
      size: 15
    ctacob: 
      type: VARCHAR
      size: 32
    ctapag: 
      type: VARCHAR
      size: 32
    codiva: 
      type: VARCHAR
      size: 4
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobreccli: 
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    codrec: 
      type: VARCHAR
      size: 10
      required: true
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobrecdoc: 
    refdoc: 
      type: VARCHAR
      size: 10
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    codrec: 
      type: VARCHAR
      size: 4
      required: true
    fecrec: 
      type: DATE
    monrec: 
      type: NUMERIC
      size: 14
      scale: 2
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobrectra: 
    numtra: 
      type: VARCHAR
      size: 10
      required: true
    refdoc: 
      type: VARCHAR
      size: 10
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    codrec: 
      type: VARCHAR
      size: 4
      required: true
    fecrec: 
      type: DATE
    monrec: 
      type: NUMERIC
      size: 14
      scale: 2
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobregges: 
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    numges: 
      type: VARCHAR
      size: 3
      required: true
    fecges: 
      type: DATE
    nomcon: 
      type: VARCHAR
      size: 50
    obsges: 
      type: VARCHAR
      size: 4000
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobtipdes: 
    coddes: 
      type: VARCHAR
      size: 3
      required: true
    desdes: 
      type: VARCHAR
      size: 50
      required: true
    codcon: 
      type: VARCHAR
      size: 32
      required: true
    tipdes: 
      type: VARCHAR
      size: 1
      required: true
    valdes: 
      type: NUMERIC
      size: 14
      scale: 2
      required: true
    diades: 
      type: NUMERIC
      size: 14
      required: true
    estret: 
      type: VARCHAR
      size: 1
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobtipmov: 
    codmov: 
      type: VARCHAR
      size: 3
      required: true
    desmov: 
      type: VARCHAR
      size: 50
    nomabr: 
      type: VARCHAR
      size: 4
    debcre: 
      type: VARCHAR
      size: 1
    ctacon: 
      type: VARCHAR
      size: 32
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobtiprec: 
    codrec: 
      type: VARCHAR
      size: 3
      required: true
    desrec: 
      type: VARCHAR
      size: 50
      required: true
    codcon: 
      type: VARCHAR
      size: 32
      required: true
    tiprec: 
      type: VARCHAR
      size: 1
      required: true
    valrec: 
      type: NUMERIC
      size: 14
      scale: 2
      required: true
    diarec: 
      type: NUMERIC
      size: 14
      required: true
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobtransa: 
    numtra: 
      type: VARCHAR
      size: 10
      required: true
    fectra: 
      type: DATE
      required: true
    codcli: 
      type: VARCHAR
      size: 15
      required: true
    destra: 
      type: VARCHAR
      size: 100
    montra: 
      type: NUMERIC
      size: 14
      scale: 2
    totdsc: 
      type: NUMERIC
      size: 14
      scale: 2
    totrec: 
      type: NUMERIC
      size: 14
      scale: 2
    tottra: 
      type: NUMERIC
      size: 14
      scale: 2
    status: 
      type: VARCHAR
      size: 1
    numcom: 
      type: VARCHAR
      size: 8
    feccom: 
      type: DATE
    fecanu: 
      type: DATE
    desanu: 
      type: VARCHAR
      size: 250
    fatipmov_id: 
      type: INTEGER
      required: true
      foreignTable: fatipmov
      foreignReference: id
    coddirec: 
      type: VARCHAR
      size: 32
      description: Código de la Dirección
    fecreg: 
      type: DATE
      description: Fecha de Registro
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
  cobfordepche: 
    _attributes: 
      description: Tabla que guarda los cheques de depositos
    numtra: 
      type: VARCHAR
      size: 10
      required: true
    numche: 
      type: VARCHAR
      size: 24
    fabancos_id: 
      type: INTEGER
      required: true
      foreignTable: fabancos
      foreignReference: id
    monche: 
      type: NUMERIC
      size: 14
      scale: 2
    cobdetfor_id: 
      type: INTEGER
      required: true
      foreignTable: cobdetfor
      foreignReference: id
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
