generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Ruta
    theme:            cidesaGenerator

    edit:
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~