default:
  http_metas:
    content-type: text/html

  metas:
    title:        Vendedores
    robots:       index, follow
    description:  Vendedores
    keywords:     Vendedores
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, observe, ajax, tools]

  has_layout:     on
  layout:         layout
