default:
  http_metas:
    content-type: text/html

  metas:
    title:        Ruta Vendedor
    robots:       index, follow
    description:  Ruta Vendedor
    keywords:     Ruta Vendedor
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, observe, ajax, tools,js/jquery.js]

  has_layout:     on
  layout:         layout_vendedor
