<?php
// auto-generated by sfViewConfigHandler
// date: 2017/05/30 13:13:16
$context  = $this->getContext();
$response = $context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'dashboardSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficaclienteSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficapedidosmesSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficafacturacionSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficacuentaxcobrarSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficaclientesmayormenosfacSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficaventaproductosSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficavendedoresmesSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficarutasmesSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'graficacoberturaestimadaSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('vendedores/highcharts.js', '');
}
else if ($templateName.$this->viewName == 'dashboardSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficaclienteSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficapedidosmesSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficafacturacionSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficacuentaxcobrarSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficaclientesmayormenosfacSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficaventaproductosSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficavendedoresmesSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficarutasmesSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else if ($templateName.$this->viewName == 'graficacoberturaestimadaSuccess')
{
  $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('dashboard', '', array ());
  $response->addStylesheet('vendedores/data_table/jquery.dataTables.css', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('vendedores/jquery-1.4.2.min.js', '');
  $response->addJavascript('vendedores/jquery-ui-1.8.5.custom.min.js', '');
  $response->addJavascript('vendedores/jquery.ui.i18n.all.js', '');
  $response->addJavascript('vendedores/thickbox-compressed.js', '');
  $response->addJavascript('highchart/code/highcharts.js', '');
  $response->addJavascript('highchart/code/highcharts-3d.js', '');
  $response->addJavascript('highchart/code/modules/exporting.js', '');
  $response->addJavascript('vendedores/data_table/jquery-1.12.4.js', '');
  $response->addJavascript('vendedores/data_table/jquery.dataTables.js', '');
}
else
{
  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout_dashboard'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vendedores', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Vendedores', false, false);
  $response->addMeta('keywords', 'Vendedores', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('tools', '');
}

