<?php
// auto-generated by sfValidatorConfigHandler
// date: 2017/05/30 12:55:13

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validatorManager->registerName('ruta_id', 1, 'La ruta no puedo estar en Blanco', 'radarventas', null, false);
  $validatorManager->registerName('facliente_id', 1, 'El cliente no puede estar blanco', 'radarventas', null, false);
  $validatorManager->registerName('vendedores_id', 1, 'El vendedor no puede estar en blanco', 'radarventas', null, false);
  $validatorManager->registerName('fecha', 1, 'La fecha no puede estar blanco', 'radarventas', null, false);
  $validatorManager->registerName('status', 1, 'El estatus no puede estar blanco', 'radarventas', null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
