<?php
// auto-generated by cidesaSecurityConfigHandler
// date: 2017/05/30 13:12:32
$this->security = array (
  'all' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_8',
        2 => 'dashboard_15',
        3 => 'dashboard_11',
        4 => 'vendedores_8',
        5 => 'vendedores_15',
        6 => 'vendedores_11',
      ),
    ),
  ),
  'index' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_8',
        2 => 'dashboard_15',
        3 => 'dashboard_11',
        4 => 'vendedores_8',
        5 => 'vendedores_15',
        6 => 'vendedores_11',
      ),
    ),
  ),
  'list' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_8',
        2 => 'dashboard_15',
        3 => 'dashboard_11',
        4 => 'vendedores_8',
        5 => 'vendedores_15',
        6 => 'vendedores_11',
      ),
    ),
  ),
  'delete' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_15',
        2 => 'vendedores_8',
        3 => 'vendedores_15',
        4 => 'vendedores_11',
      ),
    ),
  ),
  'ajaxdelete' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_15',
        2 => 'vendedores_8',
        3 => 'vendedores_15',
        4 => 'vendedores_11',
      ),
    ),
  ),
  'anular' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_15',
        2 => 'vendedores_8',
        3 => 'vendedores_15',
        4 => 'vendedores_11',
      ),
    ),
  ),
  'salvaranu' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_15',
        2 => 'vendedores_8',
        3 => 'vendedores_15',
        4 => 'vendedores_11',
      ),
    ),
  ),
  'save' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_15',
        2 => 'dashboard_11',
        3 => 'vendedores_8',
        4 => 'vendedores_15',
        5 => 'vendedores_11',
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_8',
        2 => 'dashboard_15',
        3 => 'dashboard_11',
        4 => 'vendedores_8',
        5 => 'vendedores_15',
        6 => 'vendedores_11',
      ),
    ),
  ),
  'create' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dashboard_11',
        2 => 'dashboard_15',
        3 => 'vendedores_8',
        4 => 'vendedores_15',
        5 => 'vendedores_11',
      ),
    ),
  ),
);
