<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/05/30 12:58:47
sfConfig::add(array(
  'app_autenticacion' => 'autenticacion',
  'app_max_per_page' => 15,
  'app_this' => 'herramientas',
));
