<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/05/30 12:58:47
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'catalogo',
        1 => 'admin',
      ),
    ),
  ),
);
