<?php
// auto-generated by PropelCidesa
// date: 2017/05/30 12:55:13
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php echo form_tag('radarventas/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($radarventas, 'getId') ?>

<?php
  $fields = RadarventasPeer::getFieldNames();

  if(array_search('Codalmusu', $fields))
  {  ?>
  <h2 class="h2" onclick="javascript: return $('divusualms').toggle();"><?php echo __('Almacenes') ?></h2>
  <fieldset id="sf_fieldset_usualms" class="">
  <div class="form-row" id="divusualms">
    <?php echo label_for('radarventas[codalmusu]', __('Almacenes Por Usuario: '), 'class="required" Style="text-align:left; width:150px"') ?>
    <div class="content">
    <?php
      $almacenes = $sf_user->getAttribute('usualms',array());
      if(count($almacenes)>0){
        $keys = array_keys($almacenes);
        $codalm = $keys[0];
      }else $codalm = '';
      if($codalm == '') echo label_for('radarventas[codalmusu]', __('Usuario sin Almacen Asociado'), 'class="required" Style="text-align:left; width:150px"').'<br><br><br>';
      else echo select_tag('radarventas[codalmusu]',options_for_select($almacenes,$radarventas->getCodalmusu()!='' ? $radarventas->getCodalmusu() : $codalm), ( ($radarventas->getId()) ? 'disabled=true' : '').' style=width:500px');
    ?>
    </div>
  </div>
  </fieldset>
<?php } ?>



<fieldset id="sf_fieldset_none" class="">

<div class="form-row" id="divNONE">
<div id="divruta_id">
  <?php if($labels['radarventas{ruta_id}']!='.:') { ?>
  <?php echo label_for('radarventas[ruta_id]', __($labels['radarventas{ruta_id}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('radarventas{ruta_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('radarventas{ruta_id}')): ?>
    <?php echo form_error('radarventas{ruta_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('ruta_id', array('type' => 'edit', 'radarventas' => $radarventas,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['radarventas{ruta_id}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcliente_vendedor_por_ruta">
  <?php if($labels['radarventas{cliente_vendedor_por_ruta}']!='.:') { ?>
  <?php echo label_for('radarventas[cliente_vendedor_por_ruta]', __($labels['radarventas{cliente_vendedor_por_ruta}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('radarventas{cliente_vendedor_por_ruta}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('radarventas{cliente_vendedor_por_ruta}')): ?>
    <?php echo form_error('radarventas{cliente_vendedor_por_ruta}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('cliente_vendedor_por_ruta', array('type' => 'edit', 'radarventas' => $radarventas,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['radarventas{cliente_vendedor_por_ruta}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divregistrar_articulos">
  <?php if($labels['radarventas{registrar_articulos}']!='.:') { ?>
  <?php echo label_for('radarventas[registrar_articulos]', __($labels['radarventas{registrar_articulos}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('radarventas{registrar_articulos}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('radarventas{registrar_articulos}')): ?>
    <?php echo form_error('radarventas{registrar_articulos}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('registrar_articulos', array('type' => 'edit', 'radarventas' => $radarventas,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['radarventas{registrar_articulos}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecha">
  <?php if($labels['radarventas{fecha}']!='.:') { ?>
  <?php echo label_for('radarventas[fecha]', __($labels['radarventas{fecha}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('radarventas{fecha}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('radarventas{fecha}')): ?>
    <?php echo form_error('radarventas{fecha}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($radarventas, 'getFecha', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'radarventas[fecha]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['radarventas{fecha}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divstatus">
  <?php if($labels['radarventas{status}']!='.:') { ?>
  <?php echo label_for('radarventas[status]', __($labels['radarventas{status}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('radarventas{status}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('radarventas{status}')): ?>
    <?php echo form_error('radarventas{status}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('status', array('type' => 'edit', 'radarventas' => $radarventas,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['radarventas{status}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfafactur_id">
  <?php if($labels['radarventas{fafactur_id}']!='.:') { ?>
  <?php echo label_for('radarventas[fafactur_id]', __($labels['radarventas{fafactur_id}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('radarventas{fafactur_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('radarventas{fafactur_id}')): ?>
    <?php echo form_error('radarventas{fafactur_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_select_tag($radarventas, 'getFafacturId', array (
  'related_class' => 'Fafactur',
  'control_name' => 'radarventas[fafactur_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['radarventas{fafactur_id}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<?php include_partial('edit_actions', array('radarventas' => $radarventas)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($radarventas->getId()): ?>
<?php echo button_to(__('delete'), 'radarventas/delete?id='.$radarventas->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>

