<?php
// auto-generated by PropelCidesa
// date: 2017/05/30 12:55:13
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _filters.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>
 
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('radarventas/list', array('method' => 'get','name'=>'sf_admin_filters_form')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_facliente_id"><?php echo __('Cliente:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['facliente_id']) ? $filters['facliente_id'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Facliente',
  'text_method' => '__toString',
  'control_name' => 'filters[facliente_id]',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_vendedores_id"><?php echo __('Nombre y Apellidos del Vendedor:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['vendedores_id']) ? $filters['vendedores_id'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Vendedores',
  'text_method' => '__toString',
  'control_name' => 'filters[vendedores_id]',
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'radarventas/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_ruta_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_ruta_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_facliente_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_facliente_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_vendedores_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_vendedores_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_fafactur_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_fafactur_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_fecha)
	    {
	    	obj = document.sf_admin_filters_form.filters_fecha;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_status)
	    {
	    	obj = document.sf_admin_filters_form.filters_status;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
