<?php
// auto-generated by PropelCidesa
// date: 2017/05/30 12:55:13
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_ruta">
        <?php echo __('Ruta') ?>
          </th>
  <th id="sf_admin_list_th_detalle">
        <?php echo __('Detalle') ?>
          </th>
  <th id="sf_admin_list_th_detalle_articulos">
        <?php echo __('Detalle articulos') ?>
          </th>
  <th id="sf_admin_list_th_muestra_status">
        <?php echo __('Estatus') ?>
          </th>
