<?php
// auto-generated by PropelCidesa
// date: 2017/05/30 12:55:13
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_tabular.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

    <td><?php echo get_partial('ruta', array('type' => 'list', 'radarventas' => $radarventas)) ?></td>
      <td><?php echo get_partial('detalle', array('type' => 'list', 'radarventas' => $radarventas)) ?></td>
      <td><?php echo get_partial('detalle_articulos', array('type' => 'list', 'radarventas' => $radarventas)) ?></td>
      <td><?php echo get_partial('muestra_status', array('type' => 'list', 'radarventas' => $radarventas)) ?></td>
  